# Copyright 2021 Libre Technologies LLC
subgraphs:
  schema:
    routing_url: http://alpha:8080/graphql
    schema:
      file: ./subgraphs/schema-mod.graphql
  core:
    routing_url: http://libre-core:4002/query
    schema:
      file: ./subgraphs/core.graphql
