# Copyright 2021 Libre Technologies LLC
subgraphs:
  schema:
    routing_url: http://localhost:8080/graphql
    schema:
      file: ./subgraphs/schema-mod.graphql
  core:
    routing_url: http://localhost:4002/query
    schema:
      file: ./subgraphs/core.graphql
#  scheduler:
#    routing_url: http://localhost:10001/query
#    schema:
#      file: ./subgraphs/scheduler.graphql
#  wms:
#    routing_url: http://localhost:7001/query
#    schema:
#      file: ./subgraphs/wms.graphql
